server:
  port: 8083

api:
  security:
    token:
      secret: asynchronous

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_users
    username: admin
    password: admin

  jpa:
    hibernate:
      dll-auto: update
    show-sql: false
    database: postgresql