server:
  port: 8080
api:
  security:
    token:
      secret: asynchronous
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crud_prod_db
    username: admin
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql