api:
  security:
    token:
      secret: asynchronous

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crud_prod_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql

server:
  port: 8080